#!/bin/bash
DOWNLOAD_DIR=~/AIRMOVE_PROCESSING_DOWNLOADS/
PROCESSING_SCRIPTS_DIR=~/airmove-processing-tools/
LOG_DIR=$PROCESSING_SCRIPTS_DIR/AIRMOVE_AUTO_PROCESSING/99-logs/

PROCESSING_ENV=airmove-processing-tools

